module Doc.InstructionsSpec exposing (spec)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect
import Instructions exposing(..)


spec : Test.Test
spec =
    Test.describe "Instructions" <|
    [
        Test.describe "#hexToBitPattern" <|
            [
            Test.test "Example: 1 -- `hexToBitPattern 43 --> [False, False,...`" <|
                \() ->
                    Expect.equal
                        (
                            hexToBitPattern 43
                        )
                        (
                            [False, False, True, False, True, False, True, True]
                        )
            ]
    ]