version: 2
updates:
- package-ecosystem: elm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  cooldown:
    default-days: 14
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  cooldown:
    default-days: 14
  open-pull-requests-limit: 10
