module VerifyExamples.Chip8.FetchDecodeExecuteLoop.GetNibble3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Chip8.FetchDecodeExecuteLoop exposing (..)







spec3 : Test.Test
spec3 =
    Test.test "#getNibble: \n\n    getNibble 0 0x5678\n    --> Ok 5" <|
        \() ->
            Expect.equal
                (
                getNibble 0 0x5678
                )
                (
                Ok 5
                )