module VerifyExamples.FetchDecodeExecuteLoop.DropFirstNibble0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import FetchDecodeExecuteLoop exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#dropFirstNibble: \n\n    dropFirstNibble 0x4321\n    --> 0x321" <|
        \() ->
            Expect.equal
                (
                dropFirstNibble 0x4321
                )
                (
                0x321
                )