module VerifyExamples.FetchDecodeExecuteLoop.ToHex0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import FetchDecodeExecuteLoop exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toHex: \n\n    toHex 0x4a2f\n    --> \"4A2F\"" <|
        \() ->
            Expect.equal
                (
                toHex 0x4a2f
                )
                (
                "4A2F"
                )